### ISSUE TITLE
Error --  Unexpected token ;

### ISSUE THREAD

**Issue by yu-yang** [CapacitorSet/box-js#11]
I got the following error when running box-js against malicious javascript under REMnux(latest version)

Analyzing test.js
{ Error: Line 22: Unexpected token ;
    at constructError (/opt/box-js/node_modules/esprima/esprima.js:2406:21)
    at createError (/opt/box-js/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/opt/box-js/node_modules/esprima/esprima.js:2499:13)
    at throwUnexpectedToken (/opt/box-js/node_modules/esprima/esprima.js:2504:15)
    at expect (/opt/box-js/node_modules/esprima/esprima.js:2522:13)
    at parseForStatement (/opt/box-js/node_modules/esprima/esprima.js:4426:9)
    at parseStatement (/opt/box-js/node_modules/esprima/esprima.js:4774:24)
    at parseStatementListItem (/opt/box-js/node_modules/esprima/esprima.js:3988:16)
    at parseFunctionSourceElements (/opt/box-js/node_modules/esprima/esprima.js:4868:23)
    at parseFunctionDeclaration (/opt/box-js/node_modules/esprima/esprima.js:5016:16) lineNumber: 22, description: 'Unexpected token ;', index: 486 }

And around line 22, I do not see any ";" token and the code is js-beautified, so pretty formatted. Let me know if you need the original malicious JS file. Thanks.

**Comment by CapacitorSet** [comment]
Thank you for the report. Indeed, this error is in the sample, so please
send me the file you were trying to analyse.

If you'd like not to make it public, you can send it by mail at
capacitorset@gmail.com.
Il 09/ott/2016 02:29, "yu-yang" <notifications@github.com> ha scritto:

**Comment by CapacitorSet** [comment]
Do you have any update? I didn't get any mail.

**Comment by yu-yang** [comment]
Hello, I sent the scripts to capacitorset@gmail.com last week but it seems you did not receive it. Not sure if gmail blocked those malicious scripts. Anyway, I will try to send you again tomorrow.

**Comment by CapacitorSet** [comment]
Oh, my bad - they were in the spam folder. I'll go to bed now, I'll work on them tomorrow.

**Comment by CapacitorSet** [comment]
It appears that there was indeed an error with the scripts. At line 2, you'll notice that it says (variable names changed):

```js
for(i=0;i&lt;x;i++)
```

which, beautified, becomes `for (i = 0; i & lt; x; i++)` which, however doesn't make sense (the `for` construct takes exactly three statements). This is because the code contains `&lt;`, which is the HTML entity for `<`. If you replace `&lt;` with `<` in the file (there are two occurrences), you'll get syntactically correct code.

I tried analyzing it to find any new errors in advance: it relies on the global `event` variable, which isn't provided, so I created it:

```js
event = {
    target: {
        info: {
            setakoan: "???"
        },
        eval: eval
    }
}
```

However, `event.target.info.setakoan` needs an actual value, because it's needed for decoding. It's somewhere in the PDF file; see if you can extract it and run the analysis with that. You can also send me the file and I'll try to add support directly in box-js.

**Comment by CapacitorSet** [comment]
Closing this for now, I'll reopen the issue if there are updates.

**Comment by Nwinternights** [comment]
same error here
https://malwr.com/analysis/ZmQ5MzY3OWQ1YmQ2NDU0OThhMWJlMzdmNjEzYzZiN2Q/

**Comment by CapacitorSet** [comment]
It also throws an error in standard Node.js:

```
/ram/1f040baa9f251d6a2612d2b1ea9d3bbb3abea2cd14de609e66fbb415fab9e7bb.bin:25
function String.prototype.r(){
               ^

SyntaxError: Unexpected token .
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

I think that's a quirk of JScript that one will have to work around, unfortunately, though I could reasonably push a fix that replaces `function (\w+)\.prototype.(\w+)` into `$1.prototype.$2 = function`. I'll do that in minutes.

**Comment by CapacitorSet** [comment]
Yup. I changed that, but it still doesn't work, I suspect because JScript hoists the function (it moves the prototype declaration before everything else) whereas JavaScript doesn't.
