### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by StefanKelm** [CapacitorSet/box-js#52]
After a fresh git pull box-js no longer analyses any files. Everytime I run box-js the following error is shown:

```
/usr/local/lib/node_modules/box-js/emulator/WMI.js:5
const diskSize = Math.floor(Math.random() * (10 ** 11));
                                                 ^
SyntaxError: Unexpected token *
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/box-js/analyze.js:322:13)
    at Module._compile (module.js:570:32)
```

I'm running Ubuntu 14.04.5 LTS.

**Comment by CapacitorSet** [comment]
The `**` operator was introduced in ES7, which was in Node 7.0. You can upgrade Node.js to 7.0, or upgrade box-js to 1.9.10 which I just pushed.

(Ping @ALange who was having the same issue)

**Comment by StefanKelm** [comment]
Awesome. That was fast. Thank you. :-)
