### ISSUE TITLE
Trace: Table win32_service not implemented!

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#56]
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
[info] Script read environment variable userprofile
Trace: Table win32_service not implemented!
    at Object.kill (/usr/local/lib/node_modules/box-js/lib.js:29:10)
    at getTable (/usr/local/lib/node_modules/box-js/emulator/WMI.js:66:7)
    at Proxy.ExecQuery (/usr/local/lib/node_modules/box-js/emulator/WMI.js:101:11)
    at Object.apply (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/contextify.js:288:34)
    at ccerkvkjkxyyirdz (eval at Function (vm.js:103:41), <anonymous>:38:40)
    at eval (eval at Function (vm.js:103:41), <anonymous>:58:5)
    at ceyuzm (vm.js:125:23)
    at vm.js:127:1
    at Script.runInContext (vm.js:74:29)
    at VM.run (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/main.js:204:72)
Exiting (use --no-kill to just simulate a runtime error).

Sample : https://www.reverse.it/sample/a00c774dc807919c5b7d97ff949cf004cd00d8ee17970639527aba415a823542?environmentId=100
Best regards

**Comment by psrok1** [comment]
Main part:
https://0bin.net/paste/WjNyJlvN9h+SSfVF#pcK2WJgcW-jXNiGdodmbKXqcuozsZSclBYrv81f8ZIZ
