### ISSUE TITLE
Unknown ActiveXObject adodb.connection

### ISSUE THREAD

**Issue by utkonos** [CapacitorSet/box-js#58]
This is an unknown ActiveXObject where --no-kill does not work. The sample is:
https://www.virustotal.com/gui/file/12298dfb14f426e2c5191dc22e54832df6bdfde374032b2264faadbf898b9e9f/detection

```
# box-js --timeout 60 --no-kill sample.js
/root/box-js-master/node_modules/vm2/lib/main.js:218
			throw this._internal.Decontextify.value(e);
			^

Error: Unknown ActiveXObject adodb.connection
    at Object.kill (/root/box-js-master/lib.js:28:9)
    at new ActiveXObject (/root/box-js-master/analyze.js:488:8)
    at Object.construct (/root/box-js-master/node_modules/vm2/lib/contextify.js:300:33)
    at gxO (vm.js:189:15)
    at vm.js:347:8
    at Script.runInContext (vm.js:137:20)
    at VM.run (/root/box-js-master/node_modules/vm2/lib/main.js:212:72)
    at Object.<anonymous> (/root/box-js-master/analyze.js:451:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)

 * If the error is about a weird "Unknown ActiveXObject", try --no-kill.
 * Otherwise, report a bug at https://github.com/CapacitorSet/box-js/issues/ .
```

**Comment by Eshaan7** [comment]
Same issue while running with Docker.
