### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ahezza** [CapacitorSet/box-js#60]
Here's the error I get when trying to run a sample:

```
\# box-js --timeout 300 sample.js

/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/main.js:297
			throw this._internal.Decontextify.value(e);
			^
ReferenceError: document is not defined
    at vm.js:108:1
    at Script.runInContext (vm.js:107:20)
    at VM.run (/usr/local/lib/node_modules/box-js/node_modules/vm2/lib/main.js:291:64)
    at Object.<anonymous> (/usr/local/lib/node_modules/box-js/analyze.js:442:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

 * If the error is about a weird "Unknown ActiveXObject", try --no-kill.
 * Otherwise, report a bug at https://github.com/CapacitorSet/box-js/issues/ .
```
Done some Googling and can't find a solution to this

**Comment by CapacitorSet** [comment]
Refer to this comment: https://github.com/CapacitorSet/box-js/issues/59#issuecomment-539659758

It describes the same kind of issue, just with a different feature.

Il 11 ottobre 2019 15:51:35 CEST, ahezza <notifications@github.com> ha scritto:

**Comment by ahezza** [comment]
Thanks for your help
